export const PermissionsRegistry = {
  DASHBOARD: {
    VIEW: "DASHBOARD.VIEW",
  },

  USER: {
    VIEW: "USER.VIEW",
    CREATE: "USER.CREATE",
    UPDATE: "USER.UPDATE",
    DELETE: "USER.DELETE",
  },

  ROLE: {
    VIEW: "ROLE.VIEW",
    CREATE: "ROLE.CREATE",
    UPDATE: "ROLE.UPDATE",
    DELETE: "ROLE.DELETE",
    ASSIGN_PERMISSIONS: "ROLE.ASSIGN_PERMISSIONS",
  },

  PERMISSION: {
    VIEW: "PERMISSION.VIEW",
    ASSIGN: "PERMISSION.ASSIGN",
  },

  TENANT: {
    VIEW: "TENANT.VIEW",
    CREATE: "TENANT.CREATE",
    UPDATE: "TENANT.UPDATE",
    DELETE: "TENANT.DELETE",
  },

  PRODUCT: {
    VIEW: "PRODUCT.VIEW",
    CREATE: "PRODUCT.CREATE",
    UPDATE: "PRODUCT.UPDATE",
    DELETE: "PRODUCT.DELETE",
    IMPORT: "PRODUCT.IMPORT",
    EXPORT: "PRODUCT.EXPORT",
  },

  CATEGORY: {
    VIEW: "CATEGORIES.VIEW",
    CREATE: "CATEGORIES.CREATE",
    UPDATE: "CATEGORIES.UPDATE",
    DELETE: "CATEGORIES.DELETE",
  },

  BRAND: {
    VIEW: "BRANDS.VIEW",
    CREATE: "BRANDS.CREATE",
    UPDATE: "BRANDS.UPDATE",
    DELETE: "BRANDS.DELETE",
  },

  UNIT: {
    VIEW: "UNITS.VIEW",
    CREATE: "UNITS.CREATE",
    UPDATE: "UNITS.UPDATE",
    DELETE: "UNITS.DELETE",
  },

  WAREHOUSE: {
    VIEW: "WAREHOUSES.VIEW",
    CREATE: "WAREHOUSES.CREATE",
    UPDATE: "WAREHOUSES.UPDATE",
    DELETE: "WAREHOUSES.DELETE",
  },

  STOCK: {
    VIEW: "STOCK.VIEW",
    ADJUST: "STOCK.ADJUST",
    IMPORT: "STOCK.IMPORT",
    EXPORT: "STOCK.EXPORT",
  },

  STOCK_TRANSFER: {
    VIEW: "STOCK_TRANSFER.VIEW",
    CREATE: "STOCK_TRANSFER.CREATE",
    UPDATE: "STOCK_TRANSFER.UPDATE",
    DELETE: "STOCK_TRANSFER.DELETE",
    APPROVE: "STOCK_TRANSFER.APPROVE",
  },

  SUPPLIER: {
    VIEW: "SUPPLIERS.VIEW",
    CREATE: "SUPPLIERS.CREATE",
    UPDATE: "SUPPLIERS.UPDATE",
    DELETE: "SUPPLIERS.DELETE",
    EXPORT: "SUPPLIERS.EXPORT",
  },

  CUSTOMER: {
    VIEW: "CUSTOMERS.VIEW",
    CREATE: "CUSTOMERS.CREATE",
    UPDATE: "CUSTOMERS.UPDATE",
    DELETE: "CUSTOMERS.DELETE",
    EXPORT: "CUSTOMERS.EXPORT",
  },

  PURCHASE: {
    VIEW: "PURCHASES.VIEW",
    CREATE: "PURCHASES.CREATE",
    UPDATE: "PURCHASES.UPDATE",
    DELETE: "PURCHASES.DELETE",
    APPROVE: "PURCHASES.APPROVE",
    EXPORT: "PURCHASES.EXPORT",
  },

  PURCHASE_RETURN: {
    VIEW: "PURCHASE_RETURNS.VIEW",
    CREATE: "PURCHASE_RETURNS.CREATE",
    UPDATE: "PURCHASE_RETURNS.UPDATE",
    DELETE: "PURCHASE_RETURNS.DELETE",
    APPROVE: "PURCHASE_RETURNS.APPROVE",
  },

  SALE: {
    VIEW: "SALES.VIEW",
    CREATE: "SALES.CREATE",
    UPDATE: "SALES.UPDATE",
    DELETE: "SALES.DELETE",
    APPROVE: "SALES.APPROVE",
    EXPORT: "SALES.EXPORT",
  },

  SALES_RETURN: {
    VIEW: "SALES_RETURNS.VIEW",
    CREATE: "SALES_RETURNS.CREATE",
    UPDATE: "SALES_RETURNS.UPDATE",
    DELETE: "SALES_RETURNS.DELETE",
    APPROVE: "SALES_RETURNS.APPROVE",
  },

  PAYMENT: {
    VIEW: "PAYMENTS.VIEW",
    CREATE: "PAYMENTS.CREATE",
    UPDATE: "PAYMENTS.UPDATE",
    DELETE: "PAYMENTS.DELETE",
    EXPORT: "PAYMENTS.EXPORT",
  },

  REPORT: {
    VIEW: "REPORTS.VIEW",
    EXPORT: "REPORTS.EXPORT",
  },

  NOTIFICATION: {
    VIEW: "NOTIFICATIONS.VIEW",
    UPDATE: "NOTIFICATIONS.UPDATE",
  },

  AUDIT_LOG: {
    VIEW: "AUDIT_LOGS.VIEW",
    EXPORT: "AUDIT_LOGS.EXPORT",
  },
};
